### ISSUE TITLE
也用 3.4， 编辑没问题，在华为手机（API 28）和平板上（API 26）都是一片空白，啥都没有反应。

### ISSUE THREAD

**Issue by NanyangTaiji** [tainzhi/VideoPlayer#1]

**Comment by tainzhi** [comment]
我昨晚重构了UI，打算增加多个用户入口：本地视频，斗鱼直播，收藏，电视，美剧。
正在开发中，因为我最近在找工作，需要抽出一部分时间做android面试题、投递简历等等。后续会把整个demo做完成。这毕竟是我的一个展示窗口，我也是一个完美主义者，后续肯定开发出来的。

谢谢你的关注哈。

**Comment by tainzhi** [comment]
你在manifest中的启动activity中，把MainActivity改成HomeActivity就可以了。我本来是要把HomeActivity重构成Fragment，来显示本地视频的

**Comment by NanyangTaiji** [comment]
谢谢回费，祝你一切顺利！

**Comment by NanyangTaiji** [comment]
眼拙，找不到HomeActivity.

**Comment by tainzhi** [comment]
终于改好了, 重写了好多. 目前这版[2a1748cf918](https://github.com/tainzhi/VideoPlayer/tree/2a1748cf918cd11eb26f749feb3a67024d5b339f)可以运行了, 不会出现你说的bug. 现在可以不用管什么HomeActivity或者其他的. 
现在的问题(有些可能导致crash): 
- 某些视频的缩略图无法通过ContentProvider查询到, 比如从网站通过插件下载的小视频, 格式不支持. 
- 某些视频的拍摄时间无法通过MediaMetadataRetriever获取到, 即没有Metadata
- 待重构成MVP架构, 使用RxJava等
- 缩略图的获取方式要往优化的方向走, 比如使用RxJava, Bitmap相关, 缓存, glide的使用等等等
